export const SET_GEOLOCATION = "SET_GEOLOCATION"
export const STORE_NEARBY = "STORE_NEARBY"

export const FETCH_RESTAURANT = "FETCH_RESTAURANT"
export const STORE_RESTAURANT_DETAILS = "STORE_RESTAURANT_DETAILS"


